import test from 'node:test'; import assert from 'node:assert/strict';
import {openLibraryCover,googleBooksUrl,openLibraryUrl,bnfSruUrl,parseGoogleBooks,parseOpenLibrary,parseBnfDublinCore,mergeCandidates,fetchMetadata} from '../src/metadata.js';
const isbn='9782203237766';
test('URLs fournisseurs exactes',()=>{assert.match(openLibraryCover(isbn),/covers\.openlibrary\.org/);assert.match(googleBooksUrl(isbn),/q=isbn%3A9782203237766/);assert.equal(new URL(openLibraryUrl(isbn)).searchParams.get('isbn'),isbn);assert.equal(new URL(bnfSruUrl(isbn)).searchParams.get('query'),'bib.isbn adj "9782203237766"')});
test('parse Google Books',()=>{const x=parseGoogleBooks({items:[{id:'x',volumeInfo:{title:'T',authors:['A'],publisher:'P',imageLinks:{thumbnail:'http://x'}}}]});assert.deepEqual(x[0].authors,['A']);assert.equal(x[0].coverUrl,'https://x')});
test('parse OpenLibrary',()=>{const x=parseOpenLibrary({docs:[{key:'/works/1',edition_key:['OL1M'],title:'T',publisher:['P'],author_name:['A'],first_publish_year:2022,isbn:[isbn],cover_i:42}]});assert.equal(x[0].publisher,'P');assert.equal(x[0].sourceId,'OL1M');assert.deepEqual(x[0].authors,['A']);assert.match(x[0].coverUrl,/covers\.openlibrary\.org/);assert.deepEqual(parseOpenLibrary({error:'x'}),[])});
test('parse BnF Dublin Core',()=>{const xml='<srw:numberOfRecords>1</srw:numberOfRecords><dc:title>Album</dc:title><dc:creator>Auteur</dc:creator><dc:publisher>Ed</dc:publisher><dc:date>2022</dc:date>';const x=parseBnfDublinCore(xml);assert.equal(x[0].title,'Album');assert.deepEqual(parseBnfDublinCore('<srw:numberOfRecords>0</srw:numberOfRecords>'),[])});
test('fusion conserve données utilisateur',()=>{const x=mergeCandidates({isbn,title:'Mon titre',publisher:null},[{source:'bnf',title:'Autre',publisher:'Ed'}]);assert.equal(x.album.title,'Mon titre');assert.equal(x.album.publisher,'Ed');assert.ok(x.album.coverUrl)});
test('fetchMetadata isole les pannes',async()=>{let n=0;const fake=async url=>{n++;if(url.includes('googleapis'))return{ok:true,json:async()=>({items:[{id:'g',volumeInfo:{title:'Google'}}]})};if(url.includes('openlibrary'))throw new Error('down');return{ok:true,text:async()=>'<srw:numberOfRecords>1</srw:numberOfRecords><dc:title>BnF</dc:title>'}};const out=await fetchMetadata(isbn,{fetchImpl:fake});assert.equal(n,3);assert.equal(out.length,2)});
